### ISSUE TITLE
Stateful Layout not working if stateContent is not defined

### ISSUE THREAD

**Issue by flolom** [faberNovel/stateful-layout#21]
If I use the stateful-layout without having set the default "stateContent" in the XML layout , the state ids are not found when I use `showState`.

```
java.util.NoSuchElementException: 2131362302 was not found in this StatefulLayout.
    at com.fabernovel.statefullayout.StatefulLayout.get(StatefulLayout.kt:181)
    at com.fabernovel.statefullayout.StatefulLayout.showState(StatefulLayout.kt:160)
```

example : 

```
<com.fabernovel.statefullayout.StatefulLayout>
    <com.fabernovel.statefullayout.State
        id="@+id/stateContentOne" />
    <com.fabernovel.statefullayout.State
        id="@+id/stateContentTwo" />
</com.fabernovel.statefullayout.StatefulLayout>
```

```
statefulLayout.showState(R.id.stateContentOne) // crashes
```

**Comment by sjcqs** [comment]
@flolom 
Here's two potential fixes, which one do you prefer:

## 1. With a breaking change
- Remove `stateContent`
- Remove `showContent` extension
- StatefulLayout's`initialStateId` will be either:
    - Declared `initialState` in the layout
    - Latest state in the layout

## 2. No breaking but can yield unexpected behaviors
- By default `stateContent` is an empty layout

**Comment by sjcqs** [comment]
A third option could be to make it compulsory to declare a `stateContent` view.

**Comment by flolom** [comment]
In some cases you may want to display your content with different layout (depending on the content you received). You may want to use the statefullayout in this case, as a view container, and you will have different possible "states" (= layout) for your content. Forcing to have a single "stateContent" might not be great in this case

I think it's best to either:
* have a default empty `stateContent` with a very light view, juste as the `Space` view
* allow the stateful to have a nullable "currentState" and juste hide all the states in this case

**Comment by flolom** [comment]
nope, not working : 

```
android.view.InflateException: Binary XML file line #91 in com.sampleproject:layout/my_layout: 2131362302 was not found in this StatefulLayout.
    Caused by: java.util.NoSuchElementException: 2131362302 was not found in this StatefulLayout.
        at com.fabernovel.statefullayout.StatefulLayout.get(StatefulLayout.kt:209)
        at com.fabernovel.statefullayout.StatefulLayout.onFinishInflate(StatefulLayout.kt:141)
        ...
```

**Comment by sjcqs** [comment]
I just tried it and it worked for me 🤔

**Comment by sjcqs** [comment]
Are you using `showContent()` extension instead of `showState(R.id.stateContentTwo` ? 

`showContent()` = `showState(R.id.stateContent)`

**Comment by sjcqs** [comment]
Ok, I just replicated it when declaring no `initialIState`
