### ISSUE TITLE
Add an option to waits a minimum amount of time before showing a state

### ISSUE THREAD

**Issue by sjcqs** [faberNovel/stateful-layout#25]
Inspired by the behavior of [`ContentLoadingProgressBar`](https://developer.android.com/reference/androidx/core/widget/ContentLoadingProgressBar) this would allow to prevent content flashing. 

Ideally, this should be set per states. This requires some amount of work to pull-off and they might be some tricky edge cases. 

For references: 
https://developer.android.com/reference/androidx/core/widget/ContentLoadingProgressBar

**Comment by AchrafAmil** [comment]
What about debouncing calls to showState(..) with a default debounce duration of 0 millis ?

Developers interested in making states remain for at least X millis (e.g. to avoid blinking) will simply change the debounce duration to X.

**Comment by sjcqs** [comment]
That could be a good solution 👍. They might be some edge-case (like handling the real target state and not the previous one). 

You're welcome to create a PR 😉

**Comment by AchrafAmil** [comment]
Actually a debounce would have introduced a delay in every state change, not good.

PR created with a better behavior : 


 * If requests are chained (almost zero milliseconds in between) then all will be ignored except for
 * the latest one.
 *
 * If one or many requests are sent during the [minimalTimeBetweenRequests] after a request has been
 * handled then only the most recent one will be forwarded to the handler.

**Comment by sjcqs** [comment]
Fixed by #85
