### ISSUE TITLE
Continuous delivery flow

### ISSUE THREAD

**Issue by sjcqs** [faberNovel/stateful-layout#37]
## Automate version code & name (moved to #48) 
1. Version name: <git describe>
2. Version code: tag count + arbitrary offset
## Automate release
1. Create a branch named `release/<sem_version>` in which: 
  - `CHANGELOG.md`is updated
2. Create the PR onto `master`
3. Once the PR is merge onto `master`:
    The continuous delivery workflow should:
    1. Build the AAR file
    2. Extract the relevant `CHANGELOG.md` part
    3. Create the github release
    4. (**REALLY** Optional) Create a silly release name generator

**Comment by sjcqs** [comment]
@AchrafAmil If you want to tackle this one, assign yourself on it :)

**Comment by vincentbrison** [comment]
The behavior is a bit different, but this might helps a bit https://github.com/faberNovel/docker-android/blob/develop/.github/workflows/cd_flow_release.yml
