### ISSUE TITLE
Support Android Studio Preview

### ISSUE THREAD

**Issue by vincentbrison** [faberNovel/stateful-layout#56]
Is Android Studio layout preview supported? For now if I am using the lib in a screen, AS will present a blank screen. I tried using `tools:initialState="@id/stateContent"` but it did not do much :( .

**Comment by sjcqs** [comment]
Seems like it's broken. 

I don't know how the preview is rendered thought. 

Do you have any input before I take a look ?

**Comment by vincentbrison** [comment]
Saw that on private project. But you should be able to see the issue from any xml layout containing a stateful layout as a root layout I guess.
