### ISSUE TITLE
Make Stateful class open

### ISSUE THREAD

**Issue by Nicolarius** [faberNovel/stateful-layout#82]
Is it possible to make **StatefulLayout** class non final ? It should be helpful for <merge> customView usecase with Stateful as root.

**Comment by sjcqs** [comment]
Why would you create a custom view extending StatefulLayout ?

**Comment by Nicolarius** [comment]
I have to implement a two states customview

**Comment by Nicolarius** [comment]
Here is the relative PR : https://github.com/faberNovel/stateful-layout/pull/83
