### ISSUE TITLE
Advanced animations

### ISSUE THREAD

**Issue by kelianClerc** [faberNovel/stateful-layout#9]
Is it possible to create advanced for state transitions ?
Given a state with a TextView on top of a Button, I want the TextView to translate to the left while the Button goes to the right.

**Comment by sjcqs** [comment]
`StatefulLayout` and `State` both expose `enterAnimation` and `exitAnimation`. 

Using `AnimationSet` to group the animations, it should be enough right ? 

I'll try it out to test it.
