### ISSUE TITLE
Hide button in Error state if onRetryListener is null

### ISSUE THREAD

**Issue by kelianClerc** [faberNovel/stateful-layout#90]
The extension showError allow the developer to pass a nullable onRetryListener.
In my opinion, the retry button shouldn't appear if no listener is passed.

**Comment by sjcqs** [comment]
The pull request tab is waiting for you sweet magic code

**Comment by sjcqs** [comment]
see https://github.com/faberNovel/stateful-layout/pull/91#issuecomment-696540770
